from __future__ import annotations


BIOLOGY_SIGNATURES = {
    "interferon_antiviral_response": {
        "description": "Interferon-stimulated antiviral response.",
        "expected_direction": "case_up",
        "genes": [
            "ISG15",
            "IFIT1",
            "IFIT2",
            "IFIT3",
            "IFI6",
            "IFI44",
            "IFI44L",
            "MX1",
            "MX2",
            "OAS1",
            "OAS2",
            "OAS3",
            "OASL",
            "IRF7",
            "IRF9",
            "STAT1",
            "STAT2",
            "RSAD2",
            "DDX58",
            "HERC5",
            "HERC6",
            "UBE2L6",
            "XAF1",
            "GBP1",
            "GBP2",
            "IFITM1",
            "IFITM2",
            "IFITM3",
        ],
    },
    "inflammatory_myeloid_activation": {
        "description": "Inflammatory monocyte / myeloid activation.",
        "expected_direction": "case_up",
        "genes": [
            "S100A8",
            "S100A9",
            "S100A12",
            "IL1B",
            "TNF",
            "CXCL2",
            "CXCL3",
            "CXCL8",
            "CCL2",
            "CCL3",
            "CCL4",
            "NFKBIA",
            "NFKBIZ",
            "IER3",
            "JUN",
            "FOS",
        ],
    },
    "antigen_presentation_mhc": {
        "description": "Antigen presentation and MHC activity.",
        "expected_direction": "case_up",
        "genes": [
            "HLA-DRA",
            "HLA-DRB1",
            "HLA-DPA1",
            "HLA-DPB1",
            "HLA-DQA1",
            "HLA-DQB1",
            "HLA-A",
            "HLA-B",
            "HLA-C",
            "B2M",
            "TAP1",
            "TAP2",
            "CD74",
        ],
    },
    "cytotoxic_t_nk_activation": {
        "description": "Cytotoxic T cell / NK cell activation.",
        "expected_direction": "case_up",
        "genes": [
            "NKG7",
            "GNLY",
            "PRF1",
            "GZMB",
            "GZMA",
            "GZMK",
            "IFNG",
            "KLRD1",
            "KLRF1",
            "KLRB1",
            "FCGR3A",
            "CTSW",
        ],
    },
    "t_cell_exhaustion_checkpoint": {
        "description": "T cell exhaustion and checkpoint-associated state.",
        "expected_direction": "case_up",
        "genes": [
            "PDCD1",
            "CTLA4",
            "LAG3",
            "HAVCR2",
            "TIGIT",
            "TOX",
            "CXCL13",
            "ENTPD1",
            "LAYN",
            "TNFRSF9",
            "ICOS",
        ],
    },
    "b_cell_plasma_activation": {
        "description": "B cell / plasma cell activation.",
        "expected_direction": "case_up",
        "genes": [
            "MS4A1",
            "CD79A",
            "CD79B",
            "BANK1",
            "CD74",
            "MZB1",
            "XBP1",
            "JCHAIN",
            "IGHG1",
            "IGHG3",
            "IGKC",
        ],
    },
    "cell_cycle_proliferation": {
        "description": "Cell-cycle and proliferative activity.",
        "expected_direction": "case_up",
        "genes": [
            "MKI67",
            "TOP2A",
            "STMN1",
            "TUBB",
            "HMGB2",
            "PCNA",
            "MCM2",
            "MCM3",
            "MCM4",
            "MCM5",
            "MCM6",
            "MCM7",
            "TYMS",
            "UBE2C",
        ],
    },
    "complement_macrophage_program": {
        "description": "Complement-associated macrophage / monocyte program.",
        "expected_direction": "case_up",
        "genes": [
            "C1QA",
            "C1QB",
            "C1QC",
            "APOE",
            "APOC1",
            "LST1",
            "TYROBP",
            "FCER1G",
            "CTSS",
            "AIF1",
            "MSR1",
            "MARCO",
        ],
    },
}


def normalize_gene_symbol(gene: str) -> str:
    if gene is None:
        return ""

    return str(gene).strip().upper()
